### ISSUE TITLE
hi,I have some question,could this code be used for far-filed sound localization ?  this mic array is linear array or not ?

### ISSUE THREAD

**Issue by shanhaidexiamo** [lowtraxx/respeaker_doa_detection#1]

**Comment by lowtraxx** [comment]
This specific implementation is for the non linear 4mics hat (https://www.seeedstudio.com/ReSpeaker-4Mic-Array-for-Raspberry-Pi-p-2941.html). It should be possible to modify for a linear array, but as I do not posses one of those, I can not be much help there.
